### PR TITLE
Compile built assets to ES5 (fixes #18)

### LINKED ISSUE #18: create-react-app cannot create production build when react-metrics-graphics is being used
## Steps to reproduce

1. Clone [this repo](https://github.com/openjck/bug-demo-react-metrics-graphics-18)
2. `yarn`
3. `yarn build`

## Result

create-react-app is unable to create a production build because *MetricsGraphics.js* is unable to be minfied.

Here's the output of `yarn build`:

```
yarn run v1.3.2
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/react-metrics-graphics/build/MetricsGraphics.js:1:2669

Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### PR DESCRIPTION
**Pull request by wlach**

### CODE REVIEW

File: .neutrinorc.js [hunk 1]
```diff
@@ -34,5 +36,21 @@ module.exports = {
 			}
 		}],
 		'@neutrinojs/react-components',
+		(neutrino) => {
```
Comment (openjck) [inline .neutrinorc.js]: It depends on your style, but you can optionally omit the parens here. :smile:

Comment (wlach) [reply .neutrinorc.js]: Will change. I may also update the formatting while I'm at it... (stupid tabs)

**Comment by wlach** [comment]
Yep, I will make a new release shortly.
